sudo: required
dist: bionic
language: node_js
node_js: 
install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - nvm install v12.16.3
  - npm install yarn
  - yarn install
  - sudo apt-get install snapd
  - sudo snap install snapcraft --classic 
script:
  - yarn run electron:build
notifications:
  email: false